CREATE TABLE IF NOT EXISTS category
(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
    )ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS editor(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    PRIMARY KEY(id)
    )ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS author
(
    id  int UNSIGNED NOT NULL AUTO_INCREMENT,
    name  VARCHAR(20) NOT NULL,
    last_name VARCHAR(20),
    second_name VARCHAR(20),
    birthday DATE,
    PRIMARY KEY(id)
    )ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS book
(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(20),
    num_pages int,
    id_category int UNSIGNED NOT NULL,
    id_editor int UNSIGNED NOT NULL,
    isbn int(13),
    price int,
    resume VARCHAR(255),
    date_public DATE,
    PRIMARY KEY(id),
    CONSTRAINT book_category_id_fk FOREIGN KEY(id_category) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT editor_id_fk FOREIGN KEY(id_editor) REFERENCES editor(id) ON DELETE CASCADE ON UPDATE CASCADE
    )ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ranking
(
    id int UNSIGNED NOT NULL AUTO_INCREMENT,
    raking int NOT NULL,
    id_author int UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT raking_authors_id_fk FOREIGN KEY(id_author) REFERENCES author(id) ON DELETE CASCADE ON UPDATE CASCADE
    )ENGINE=INNODB DEFAULT CHARSET=utf8;